/** Auto-generated by sync_bctoolkit_resources.py — run after Excel updates */
window.BCTK_RESOURCES = [
  {
    "title": "BC Knowledge AI (NotebookLM)",
    "url": "https://notebooklm.google.com/notebook/3d1d83d8-0459-47b3-a696-55e1e26eed22?pli=1"
  },
  {
    "title": "Healthbridge YouTube",
    "url": "https://www.youtube.com/channel/UC2X36DjuYAuvjlGcoZ7Ih8w"
  },
  {
    "title": "Clinical Assistant overview (web)",
    "url": "https://www.healthbridge.co.za/clinical-assistant/"
  },
  {
    "title": "Healthbridge corporate site",
    "url": "https://www.healthbridge.co.za/"
  },
  {
    "title": "HB Clinical Help Center (home)",
    "url": "https://help.healthbridgeclinical.co.za/en"
  },
  {
    "title": "Healthbridge Clinical (EHR)",
    "url": "https://www.healthbridge.co.za/healthbridge-clinical/"
  },
  {
    "title": "myMPS tablet portal",
    "url": "https://tablet.mymps.co.za/"
  },
  {
    "title": "Questionnaires — help article",
    "url": "https://help.healthbridgeclinical.co.za/en/article/how-to-use-questionnaires-in-healthbridge-clinical"
  },
  {
    "title": "Security (Password protect /  watermark  / QR code",
    "url": "https://help.healthbridgeclinical.co.za/en/article/how-to-add-or-remove-watermarks-on-documents"
  },
  {
    "title": "Vaccination schedule",
    "url": "https://help.healthbridgeclinical.co.za/en/article/vaccination-schedule"
  },
  {
    "title": "Developmental screening",
    "url": "https://help.healthbridgeclinical.co.za/en/article/developmental-screening"
  },
  {
    "title": "Growth charts",
    "url": "https://help.healthbridgeclinical.co.za/en/article/how-to-access-growth-and-metric-charts-in-healthbridge-clinical"
  },
  {
    "title": "Pathology centre",
    "url": "https://help.healthbridgeclinical.co.za/en/article/pathology-centre"
  },
  {
    "title": "Pathology Messenger — help article",
    "url": "https://help.healthbridgeclinical.co.za/en/article/pathology-messenger"
  },
  {
    "title": "Dis-Chem integration",
    "url": "https://help.healthbridgeclinical.co.za/en/article/how-to-send-scripts-directly-to-dis-chem"
  },
  {
    "title": "SmartMeds",
    "url": "https://help.healthbridgeclinical.co.za/en/article/smartmeds"
  },
  {
    "title": "Questionnaires — video",
    "url": "https://vimeo.com/1156367316?fl=ip&fe=ec"
  },
  {
    "title": "Security Features",
    "url": "https://vimeo.com/1164612399?share=copy&fl=sv&fe=ci"
  },
  {
    "title": "The \"Paediatric Pack\"",
    "url": "https://vimeo.com/1168799843?share=copy&fl=sv&fe=ci"
  },
  {
    "title": "Custom Document Generator",
    "url": "https://vimeo.com/1124580735?share=copy"
  },
  {
    "title": "Motivation Letter:",
    "url": "https://vimeo.com/1121862873?share=copy"
  },
  {
    "title": "Medical History Summary",
    "url": "https://vimeo.com/1124181323?share=copy"
  },
  {
    "title": "Visit Summary",
    "url": "https://vimeo.com/1121814495?share=copy"
  },
  {
    "title": "Referral Letter",
    "url": "https://vimeo.com/1119822817"
  },
  {
    "title": "Clinical Insights",
    "url": "https://vimeo.com/1125800178?share=copy"
  },
  {
    "title": "Pathology Messenger — video",
    "url": "https://vimeo.com/1101194190?share=copy"
  },
  {
    "title": "Patient Summary",
    "url": "https://vimeo.com/1119720242?share=copy"
  }
];
