"""
Rebuild bctoolkit_resources.js from the BC Toolkit sheet in the HBC Case Reasons workbook.

Default path matches the common local copy under Desktop/Kaelo; override with:
  python sync_bctoolkit_resources.py "C:\\path\\to\\workbook.xlsx"
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pandas as pd

_HERE = Path(__file__).resolve().parent
OUT_JS = _HERE / "bctoolkit_resources.js"
DEFAULT_XLSX = Path(
    r"C:\Users\heleen.fengler\Desktop\Kaelo\March 2026\HBC Case Reasons -final.xlsx"
)
SHEET = "Toolkit for BCs"

URL_RE = re.compile(r"https?://\S+", re.I)


def rows_from_sheet(df: pd.DataFrame) -> list[tuple[str, str]]:
    raw_pairs: list[tuple[str, str]] = []
    for _, row in df.iterrows():
        raw_t = row.iloc[0]
        raw_u = row.iloc[1]
        if pd.isna(raw_u):
            continue
        u = str(raw_u).strip()
        m = URL_RE.search(u)
        if not m:
            continue
        url = m.group(0).rstrip(").,;]")
        title = "" if pd.isna(raw_t) else str(raw_t).strip()
        if not title:
            title = url
        raw_pairs.append((title, url))

    # Disambiguate duplicate titles (same label used for help + video rows).
    from collections import Counter

    counts = Counter(t for t, _ in raw_pairs)
    out: list[tuple[str, str]] = []
    for title, url in raw_pairs:
        t = title
        if counts[title] > 1:
            if "vimeo.com" in url:
                t = f"{title} — video"
            elif "help.healthbridgeclinical.co.za" in url:
                t = f"{title} — help article"
        out.append((t, url))
    return out


def extra_portal_links() -> list[tuple[str, str]]:
    """Stable entry points not duplicated on the Toolkit sheet."""
    return [
        (
            "BC Knowledge AI (NotebookLM)",
            "https://notebooklm.google.com/notebook/3d1d83d8-0459-47b3-a696-55e1e26eed22?pli=1",
        ),
        ("Healthbridge YouTube", "https://www.youtube.com/channel/UC2X36DjuYAuvjlGcoZ7Ih8w"),
        ("Clinical Assistant overview (web)", "https://www.healthbridge.co.za/clinical-assistant/"),
        ("Healthbridge corporate site", "https://www.healthbridge.co.za/"),
        ("HB Clinical Help Center (home)", "https://help.healthbridgeclinical.co.za/en"),
        ("Healthbridge Clinical (EHR)", "https://www.healthbridge.co.za/healthbridge-clinical/"),
        ("myMPS tablet portal", "https://tablet.mymps.co.za/"),
    ]


def main() -> None:
    xlsx = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_XLSX
    if not xlsx.is_file():
        print(f"ERROR: workbook not found: {xlsx}")
        sys.exit(1)

    df = pd.read_excel(xlsx, sheet_name=SHEET, header=None)
    from_sheet = rows_from_sheet(df)
    combined = extra_portal_links() + from_sheet

    # De-dupe exact URLs (keep first title)
    seen: set[str] = set()
    unique: list[dict[str, str]] = []
    for title, url in combined:
        key = url.split("#")[0].rstrip("/")
        if key in seen:
            continue
        seen.add(key)
        unique.append({"title": title, "url": url})

    payload = json.dumps(unique, ensure_ascii=False, indent=2)
    js = (
        "/** Auto-generated by sync_bctoolkit_resources.py — run after Excel updates */\n"
        "window.BCTK_RESOURCES = "
        + payload
        + ";\n"
    )
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"Wrote {len(unique)} resources to {OUT_JS}")


if __name__ == "__main__":
    main()
